package net.morimori0317.bestylewither.entity;

public interface ExplodeByDieConstants {
    int ENERGY_LAYER_START_TICK = 13;
    int ENERGY_LAYER_BLINKING_START_TICK = 29;
    int ENERGY_LAYER_LONG_BLINKING_END_TICK = 155;
    int EXPLODE_TICK = 20 * 10;

    int ENERGY_LAYER_LONG_BLINKING_ON_DURATION = 5;
    int ENERGY_LAYER_SHORT_BLINKING_ON_DURATION = 2;
    int ENERGY_LAYER_BLINKING_OFF_MIN_DURATION = 1;
    int ENERGY_LAYER_BLINKING_OFF_MAX_DURATION = 2;
}
