modLoader = "javafml"
loaderVersion = "[2,)"
license = "GNU LGPLv3"

[[mods]]
modId = "bestylewither"
version = "${version}"
displayName = "BE Style Wither"
displayURL = "https://modrinth.com/mod/be-style-wither"
issueTrackerURL = "https://github.com/MORIMORI0317/BEStyleWither/issues"
updateJSONURL = "https://raw.githubusercontent.com/MORIMORI0317/BEStyleWither/main/neoforge_version_check.json"
authors = "MORIMORI0317"
description = '''
This mod brings the behavior of Wither closer to Bedrock Edition.
The ikisugi wither mod...
'''
logoFile = "logo.png"

[modproperties.bestylewither]
catalogueImageIcon = "assets/bestylewither/icon.png"
configuredBackground = "minecraft:textures/block/bedrock.png"

[[dependencies.bestylewither]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bestylewither]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "bestylewither.mixins.json"
